### ISSUE TITLE
Microsoft Edge get error status

### ISSUE THREAD

**Issue by weilunc93** [RazerMS/Integration-RazerMS_JavaScript_Seamless_Integration#11]
When i click button that trigger Molpay seamless and Microsoft Edge will prompt a message to ask whether user want to allow or block the popup for the first time. If allow, i will get error status. This only happen when the popup show. After that, it work.

error_code: "P13"
error_desc: "Currency not supported here"

SDK version: latest

**Comment by tjwoon** [comment]
Hi MOLPay team. Chiming in on my colleague's post with some details.

Steps to reproduce:

1. On a Microsoft Edge browser which has never allowed or blocked the MOLPay popup before, load some demo page.
2. Call the SDK to accept a payment.
3. Browser will display a message saying that the popup has been blocked.
4. Allow the popup.
5. Popup opens, with the error given by @weilunc93 
6. If you close the popup now, and trigger the SDK to accept payment again, a new popup will open and display MOLPay landing page - no problem.

I suspect Microsoft Edge *may be* not sending POST parameters when the blocked popup is allowed by user.

**Comment by wankimmy** [comment]
Hi @tjwoon and @weilunc93 , are you still having this issue ? if no RazerMS team will close this issue
