### ISSUE TITLE
No more https://sandbox.molpay.com/ ?

### ISSUE THREAD

**Issue by zjye-idealhub** [RazerMS/Integration-RazerMS_JavaScript_Seamless_Integration#20]
I was unable to test in sandbox due to https://sandbox.molpay.com/MOLPay/API/seamless/latest/js/MOLPay_seamless.deco.js is not working any more, it return nothing

**Comment by apis17** [comment]
please change to https://sandbox.merchant.razer.com/MOLPay/API/seamless/latest/js/MOLPay_seamless.deco.js 

thanks for reporting. will update on next release

**Comment by Hibar3** [comment]
Hi, may i know what's the current sandbox Url for merchant portal?

**Comment by jimanx2** [comment]
Hi @Hibar3, please use https://sandbox.merchant.razer.com/MerchantPortal/index.php?mod=authentication&opt=login to access sandbox merchant portal.

**Comment by Hibar3** [comment]
Thanks for the prompt reply, do i need to create separate account to access the sandbox portal as well?

**Comment by jimanx2** [comment]
Yes, please reach out to Razer Merchant Services support team at support-sa@razer.com to get a sandbox account

**Comment by wankimmy** [comment]
close this issue as the issue already resolved
