### ISSUE TITLE
Javascript Example is non-standard

### ISSUE THREAD

**Issue by r0lodex** [RazerMS/Integration-RazerMS_JavaScript_Seamless_Integration#4]
https://github.com/MOLPay/Seamless_Integration/blob/master/FB%20App%20Seamless%20(example)/molpay_facebook_seamless(example).js#L26

This is a trivial one but I feel big corps should be up on standard for examples like this.
Instead of pulling a one-liner you guys could make it more readable no?

**Comment by ahmadsolehin** [comment]
not working...

**Comment by wankimmy** [comment]
hi @ahmadsolehin and @r0lodex , do let us know if the problem still persist, will close this issue if no respond

**Comment by r0lodex** [comment]
> hi @ahmadsolehin and @r0lodex , do let us know if the problem still persist, will close this issue if no respond

That's 6 years too late! We're not on Razer anymore 🤣 maybe in the future but who knows?

**Comment by wankimmy** [comment]
> > hi @ahmadsolehin and @r0lodex , do let us know if the problem still persist, will close this issue if no respond
> 
> That's 6 years too late! We're not on Razer anymore 🤣 maybe in the future but who knows?

Apology for that, normally we receive technical queries from support-sa@razer.com and technical-sa@razer.com, now we are improving our services and going to be active on Github also planning to build a developer community, stay tuned
